# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-timeago

# jekyll-seo-tag configuration
author: "Morris Clay"
url: "futureof.dev"
title: "The future of Software Development"
description: ""
twitter:
  username: "futureofdev"
  card: ""
logo: "path/to/image"

collections_dir: collections
collections:
  posts:
    output: true
  products:
    output: true

paginate: 2
paginate_path: "/page:num/"

site.url: "https://futureof.dev/"
baseurl: "/futureof.dev"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
